### ISSUE TITLE
"Flint" walletStringName should be "flint"

### ISSUE THREAD

**Issue by theInfiniteWill** [HarmonicPool/cardano-wallet-interface#10]
Not sure how recent the change was but the correct walletStringName for flint should all be lowercase. This is for the most up-to-date Flint Chrome extension

<img width="595" alt="image" src="https://user-images.githubusercontent.com/92169936/156811687-c474c6fd-8ae5-4865-81b4-fa01334f13b1.png">

**Comment by HarmonicPool** [comment]
```Wallet.stringNames``` elements (and respectively ```Wallet.Names.Wallet```) try to emulate the ```window.cardano.walletExtension.name``` value

in this case [```Wallet.Names.Flint```](https://github.com/HarmonicPool/cardano-wallet-interface/blob/main/src/Wallet/index.js#L188) value is currently ```"Flint"```, whereas the correct value should now be ```"Flint Wallet"``` as we can see from your screen.

If in your app you only use ```Wallet.Names``` properties or ```Wallet.stringNames``` elements you should have no problem.

Anyway thank you for signaling the issue, ofthen these small changes are hard to track, will change the value ASAP

**Comment by theInfiniteWill** [comment]
To clarify, the correct value should now be 'flint' and not 'flint wallet'. This bug prevents users from using flint API at all using `Wallet.stringNames` or `Wallet.stringNames`

`Wallet.stringNames` doesn't work because the cardano object is case sensitive and attempts to look for `window.cardano.Flint` instead of `window.cardano.flint`. To further explain,`Wallet.get(Wallet.Names.Flint)` will always be undefined since it passes `Wallet.get('Flint')` instead of `Wallet.get('flint')`

**Comment by HarmonicPool** [comment]
I see where your concern is

actually ```Wallet.Names``` and ```Wallet.stringNames``` elements are mapped to the respective browser API as you can se, as an example from the [```enable``` method implementation, flint API case](https://github.com/HarmonicPool/cardano-wallet-interface/blob/e4ceb551f57932c31a7e310e479efb8372769298/src/Wallet/index.js#L481)

so calling ```Wallet.enable('Flint')``` will internally call ```window.cardano.flint.enable```

I would strongly suggest using the ```Wallet.Names``` object to access various APIs, since, as in this case, changes made in the API itself might not be immediately implemented, therefore calls like ```Wallet.enable( window.cardano.flint.name )``` will result in an error because the name value has been modified between APIs version

**Comment by HarmonicPool** [comment]
I'm clòosing the issue, I hope any doubt has been clarified now!
