### ISSUE TITLE
getRewardAddresses returns undefined

### ISSUE THREAD

**Issue by Kulaneian** [HarmonicPool/cardano-wallet-interface#14]
Hi Michele,

I have been reading a bit in the code for the package and tried out some methods. I wanted to console.log the bech32 wallet address and then later render it on the screen, but I get 'undefined' back as a result. 

Any idea what could cause that?

**Comment by HarmonicPool** [comment]
I'm having a quick look at the code and ```private_getRewardAddress_bech32``` depends by [```private_getRewardAddress```](https://github.com/HarmonicPool/cardano-wallet-interface/blob/3b9451fcaf7fc79bc9e8b56f227b42657d69a21c/src/Wallet/index.js#L1025);

```private_getRewardAddress``` throws if it doesn't get a string
and ```private_getRewardAddress_bech32``` just gets that string and converts it using the standard CSL classes

I'm sure you are awaiting the function otherwise you'd get a pending promise and not ```undefined```;

I need more information on where you get undefined;

PS. be sure the wallet is staked

**Comment by Kulaneian** [comment]
I was using async await to get the data, but the 'ps' probably explains it.

The connected wallet should have a stake key or else you won't get the wallet address back?
If that is the case then it makes a lot of sense, because I was trying to get the wallet address from a wallet that didnt stake any ADA.

Thanks for the help 👍
