### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by theInfiniteWill** [HarmonicPool/cardano-wallet-interface#7]
Thanks so much for this, the project seems great!

When I try to import into a React component built with NextJs, I get the following error. Any thoughts on how to fix?

`./node_modules/@harmonicpool/cardano-wallet-interface/node_modules/@emurgo/cardano-serialization-lib-asmjs/cardano_serialization_lib_bg.js`
`Critical dependency: the request of a dependency is an expression`
`error - SyntaxError: Cannot use import statement outside a module`

## Current setup
I'm importing through
`import { Wallet } from '@harmonicpool/cardano-wallet-interface';`

I've added the suggested to next.config.js
`  webpack: (config) => {
    const experiments = config.experiments || {};
    config.experiments = {
    ...experiments,
    syncWebAssembly: true,
    };
    return config
},`

and in tsconfig.json, I've set a couple other variables suggested when finding this issue online. 
`    "lib": ["esnext"],
    "module": "commonjs",
`

**Comment by HarmonicPool** [comment]
Yeah the documentation might need to be updated, That's for sure planned

```next.config.js``` no more needs that configuration, since WASM dependencies have been removed, but having it should not give problems at least for the library code

I think the problem is due to the ```"module": "commonjs"``` in the ```tsconfig.json``` file; the library uses ESModules ```import```s statements

I would suggest changing it to ESModules instead or enabling ``"esModuleInterop": true,``` in the compiler options as follows:

```ts
"compilerOptions": {
    /* other options */
    "esModuleInterop": true,
  },
```

**Comment by theInfiniteWill** [comment]
Thanks for the reply!

I already had 
`"esModuleInterop": true,`
and fiddling with target, lib and module to various settings hasn't fixed the issue. 

My current `tsconfig.json` for reference.

````
{
  "compilerOptions": {
    "target": "ES2021",
    "lib": [
      "ES2021"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "noImplicitAny": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "jsxImportSource": "@emotion/react",
    "incremental": true
  },
  "include": [
    "next-env.d.ts",
    "**/*.ts",
    "**/*.tsx"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by HarmonicPool** [comment]
ok then, our problem is just the following line:
```Cannot use import statement outside a module```

if you have added support for ESModules but the problem persists, then most probably that is due to the fact that Next.js uses common behind the schenes

You might want to use the library only with specific components that interact with wallets and render them with ```dynamic``` ([Nextjs documentation for ```dynamic```](https://nextjs.org/docs/advanced-features/dynamic-import))

simple example:
```ts
import dynamic from 'next/dynamic';
const MyWalletComponent = dynamic( 
    () => import("../path/to/MyWalletComponent.ts"),
    { /* dynamic options as in the Nextjs docs */}
);
```

this way ESModules imports should not be a problem

**Comment by theInfiniteWill** [comment]
Got it working! Thanks so much 👍 

 I needed to dynamically import the component that imports your library!

Reference for anyone else in the future

```
const WalletConnector = dynamic(() => import('../components/WalletConnector'), {
  ssr: false,
});
```

and inside of `WalletConnector`
`import { Wallet } from '@harmonicpool/cardano-wallet-interface';`
