### ISSUE TITLE
How to parse getUtxos() to get UTXO addresses

### ISSUE THREAD

**Issue by theInfiniteWill** [HarmonicPool/cardano-wallet-interface#8]
Any advice on how to parse TransactionUnspentOutput from getUtxos(...) to UTXO addresses? 

I've seen examples but they've all required Node and not possible on the FE.

**Comment by HarmonicPool** [comment]
Hi @0xChief;

by [CIP-0030 definition of TransactionUnspentOutput](https://github.com/cardano-foundation/CIPs/tree/master/CIP-0030#transactionunspentoutput) what we are talking about is a ```CBOR``` string

to get the UTxO hash you'd have to parse the CBOR first;
you can check [Harmonic's CBOR parser](https://github.com/HarmonicPool/json-cbor-interop/blob/main/src/Cbor/index.ts#L507) in the [json-cbor-interop](https://github.com/HarmonicPool/json-cbor-interop) library

or use the library itself even if it is undocumented, all the test suites works so the current code works fine

[Harmonic has also submitted a Catalyst proposal](https://cardano.ideascale.com/c/idea/396949) to make a library that will allow easier interaction with all the technical parts of off-chain Cardano code, and a planned feature is for sure Integrating CBOR parsing optimized for Cardano Protocol structures

the library seems to interest many developers, but we actually need to be founded in order to get something done, so if you really need this feature I'd suggest having a look at the proposal too and spread the word about it

**Comment by theInfiniteWill** [comment]
Couldn't get it to work with the library you mentioned but was able to get it to work with `'@emurgo/cardano-serialization-lib-asmjs'`
